# Generated by sila2.code_generator; sila2.__version__: 0.12.2
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.storageinfoprovider import SetOutputFormat_Responses, StorageInfoProviderBase

if TYPE_CHECKING:
    from ..server import Server


class StorageInfoProviderImpl(StorageInfoProviderBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

    def get_SemanticStorageInfo(self, *, metadata: MetadataDict) -> str:
        raise NotImplementedError  # TODO

    def SetOutputFormat(self, OutputFormat: str, *, metadata: MetadataDict) -> SetOutputFormat_Responses:
        raise NotImplementedError  # TODO
